import { useEffect, useMemo, useRef, useState } from 'react';
import * as d3 from 'd3';
import anime from 'animejs';
import html2canvas from 'html2canvas';
import './HeptavertonicVisualization.css';
import {
  CANVAS_HEIGHT,
  CANVAS_WIDTH,
  FINANCIAL_DATA,
  FLOWS,
  NODE_POSITIONS,
  PERIPHERAL_NODES,
  SIMULATION_STEPS,
  TRIADS,
  TRIAD_SIZE,
  VALID_NODE_IDS,
  VERTEX_SIZE,
  type Flow,
  type PeripheralNode,
  type Triad,
  type Vertex,
} from './heptavertonicData';
import {
  deriveBalanceState,
  formatCurrency,
  getBalanceColor,
  parseStateFromHash,
  serializeStateToHash,
  type BalanceState,
} from './heptavertonicUtils';

interface NodeDetails {
  id: string;
  title: string;
  subtitle: string;
  description: string;
  accountRange?: string;
  dimension: string;
  departments: string[];
  financialSummary: string[];
}

const flowStyleMap: Record<Flow['type'], { color: string; dashArray?: string }> = {
  supply: { color: '#10B981' },
  demand: { color: '#F59E0B', dashArray: '7 5' },
  innovation: { color: '#EC4899' },
  complementary: { color: '#6366F1', dashArray: '3 4' },
  ai: { color: '#38BDF8', dashArray: '2 6' },
};

const oscillationMap: Record<keyof BalanceState, number[]> = {
  potential: [0, 0.035, -0.03, 0],
  commitment: [0, 0.025, -0.035, 0],
  performance: [0, 0.02, -0.025, 0],
  coherence: [0, 0.018, -0.018, 0],
};

function getNodeDetails(selectedId: string | null): NodeDetails | null {
  if (!selectedId) {
    return null;
  }

  const triad = TRIADS.find((item) => item.id === selectedId);
  if (triad) {
    return {
      id: triad.id,
      title: triad.name,
      subtitle: `${triad.shortLabel} · ${triad.cognitiveCenter}`,
      description: triad.description,
      accountRange: triad.accountRange,
      dimension: triad.dimension,
      departments: triad.departments,
      financialSummary: triad.financialSummary,
    };
  }

  const vertexResult = TRIADS.flatMap((item) => item.vertices.map((vertex) => ({ triad: item, vertex }))).find((item) => item.vertex.id === selectedId);
  if (vertexResult) {
    return {
      id: vertexResult.vertex.id,
      title: vertexResult.vertex.name,
      subtitle: `${vertexResult.triad.shortLabel} · ${vertexResult.vertex.cognitiveCenter}`,
      description: vertexResult.vertex.description,
      accountRange: vertexResult.vertex.accountRange,
      dimension: vertexResult.vertex.dimension,
      departments: vertexResult.vertex.departments,
      financialSummary: [`Parent Triad: ${vertexResult.triad.name}`, ...vertexResult.triad.financialSummary],
    };
  }

  const peripheralNode = PERIPHERAL_NODES.find((item) => item.id === selectedId);
  if (peripheralNode) {
    return {
      id: peripheralNode.id,
      title: peripheralNode.name,
      subtitle: peripheralNode.shortLabel,
      description: peripheralNode.description,
      accountRange: peripheralNode.accountRange,
      dimension: peripheralNode.dimension,
      departments: peripheralNode.departments,
      financialSummary: peripheralNode.financialSummary,
    };
  }

  return null;
}

function buildFinancialSummary(): NodeDetails {
  const centerLines = FINANCIAL_DATA.centers.map((center) => `${center.name}: ${formatCurrency(center.total)}`);
  const eliminationLines = FINANCIAL_DATA.eliminations.map((item) => `${item.name}: ${formatCurrency(item.value)}`);
  const adjustmentLines = FINANCIAL_DATA.adjustments.map((item) => `${item.name}: ${formatCurrency(item.value)}`);

  return {
    id: 'financial-overview',
    title: 'Consolidated Financial View',
    subtitle: 'Cognitive architecture-wide financial allocation',
    description: 'The living financial organism emerges from interactions between all seven triads, the manufacturing core, and the coherence premiums generated by metacycle alignment.',
    dimension: 'All Dimensions',
    departments: ['Centers Allocation', 'Inter-triadic Eliminations', 'Virtual Field Adjustments'],
    financialSummary: [...centerLines, ...eliminationLines, ...adjustmentLines],
  };
}

function buildFlowPath(flow: Flow) {
  const from = NODE_POSITIONS[flow.from];
  const to = NODE_POSITIONS[flow.to];
  if (!from || !to) {
    return '';
  }

  const dx = to.x - from.x;
  const dy = to.y - from.y;
  const distance = Math.hypot(dx, dy);
  const curveFactor = flow.type === 'complementary' ? 0.18 : flow.type === 'ai' ? 0.12 : 0.1;
  const controlX = (from.x + to.x) / 2 - dy * curveFactor;
  const controlY = (from.y + to.y) / 2 + dx * curveFactor;

  if (distance < 1) {
    return `M ${from.x} ${from.y} L ${to.x} ${to.y}`;
  }

  return `M ${from.x} ${from.y} Q ${controlX} ${controlY} ${to.x} ${to.y}`;
}

function getQuadraticMidpoint(flow: Flow) {
  const from = NODE_POSITIONS[flow.from];
  const to = NODE_POSITIONS[flow.to];
  if (!from || !to) {
    return { x: 0, y: 0 };
  }

  const dx = to.x - from.x;
  const dy = to.y - from.y;
  const curveFactor = flow.type === 'complementary' ? 0.18 : flow.type === 'ai' ? 0.12 : 0.1;
  const controlX = (from.x + to.x) / 2 - dy * curveFactor;
  const controlY = (from.y + to.y) / 2 + dx * curveFactor;

  return {
    x: 0.25 * from.x + 0.5 * controlX + 0.25 * to.x,
    y: 0.25 * from.y + 0.5 * controlY + 0.25 * to.y,
  };
}

function nodeMatchesQuery(node: string, query: string) {
  if (!query.trim()) {
    return true;
  }

  const normalizedQuery = query.toLowerCase();
  const details = getNodeDetails(node);
  if (!details) {
    return false;
  }

  return [
    details.title,
    details.subtitle,
    details.description,
    details.accountRange,
    details.dimension,
    ...details.departments,
    ...details.financialSummary,
  ]
    .filter(Boolean)
    .join(' ')
    .toLowerCase()
    .includes(normalizedQuery);
}

const HeptavertonicVisualization = () => {
  const initialState = useMemo(() => parseStateFromHash(window.location.hash), []);
  const [showFlows, setShowFlows] = useState(initialState.showFlows);
  const [showBalance, setShowBalance] = useState(initialState.showBalance);
  const [showFinancial, setShowFinancial] = useState(initialState.showFinancial);
  const [animationRunning, setAnimationRunning] = useState(true);
  const [selectedId, setSelectedId] = useState<string | null>(initialState.showFinancial ? 'financial-overview' : null);
  const [searchQuery, setSearchQuery] = useState(initialState.search);
  const [zoomTransform, setZoomTransform] = useState(d3.zoomIdentity.translate(0, 0).scale(1));
  const [simulationIndex, setSimulationIndex] = useState(0);
  const [simulationPlaying, setSimulationPlaying] = useState(false);

  const viewportRef = useRef<HTMLDivElement>(null);
  const exportRef = useRef<HTMLDivElement>(null);
  const potentialRef = useRef<HTMLDivElement>(null);
  const commitmentRef = useRef<HTMLDivElement>(null);
  const performanceRef = useRef<HTMLDivElement>(null);
  const coherenceRef = useRef<HTMLDivElement>(null);

  const balanceState = useMemo(() => deriveBalanceState(FINANCIAL_DATA), []);
  const selectedDetails = useMemo(() => {
    if (showFinancial && selectedId === null) {
      return buildFinancialSummary();
    }
    if (selectedId === 'financial-overview') {
      return buildFinancialSummary();
    }
    return getNodeDetails(selectedId);
  }, [selectedId, showFinancial]);

  const activeStep = SIMULATION_STEPS[simulationIndex];

  useEffect(() => {
    const serialized = serializeStateToHash({
      showFlows,
      showBalance,
      showFinancial,
      search: searchQuery,
    });
    window.history.replaceState(null, '', `${window.location.pathname}${serialized ? `#${serialized}` : ''}`);
  }, [searchQuery, showBalance, showFinancial, showFlows]);

  useEffect(() => {
    const element = viewportRef.current;
    if (!element) {
      return;
    }

    const zoomBehavior = d3
      .zoom<HTMLDivElement, unknown>()
      .scaleExtent([0.65, 2.5])
      .on('zoom', (event) => {
        setZoomTransform(event.transform);
      });

    const selection = d3.select(element);
    selection.call(zoomBehavior as never);

    return () => {
      selection.on('.zoom', null);
    };
  }, []);

  useEffect(() => {
    const animationRefs: Record<keyof BalanceState, HTMLDivElement | null> = {
      potential: potentialRef.current,
      commitment: commitmentRef.current,
      performance: performanceRef.current,
      coherence: coherenceRef.current,
    };

    (Object.keys(animationRefs) as Array<keyof BalanceState>).forEach((key) => {
      const element = animationRefs[key];
      if (!element) {
        return;
      }

      anime.remove(element);
      if (!animationRunning) {
        element.style.width = `${Math.round(balanceState[key] * 100)}%`;
        return;
      }

      anime({
        targets: element,
        width: oscillationMap[key].map((offset) => `${Math.round((balanceState[key] + offset) * 100)}%`),
        duration: 9000,
        easing: 'easeInOutSine',
        loop: true,
      });
    });

    return () => {
      Object.values(animationRefs).forEach((element) => {
        if (element) {
          anime.remove(element);
        }
      });
    };
  }, [animationRunning, balanceState]);

  useEffect(() => {
    if (!simulationPlaying) {
      return;
    }

    const timer = window.setInterval(() => {
      setSimulationIndex((current) => (current + 1) % SIMULATION_STEPS.length);
    }, 2400);

    return () => {
      window.clearInterval(timer);
    };
  }, [simulationPlaying]);

  useEffect(() => {
    if (showFinancial && !selectedId) {
      setSelectedId('financial-overview');
    }
    if (!showFinancial && selectedId === 'financial-overview') {
      setSelectedId(null);
    }
  }, [selectedId, showFinancial]);

  const matchedNodeIds = useMemo(() => {
    return new Set(
      [...VALID_NODE_IDS].filter((id) => nodeMatchesQuery(id, searchQuery)),
    );
  }, [searchQuery]);

  const transformStyle = {
    transform: `translate(${zoomTransform.x}px, ${zoomTransform.y}px) scale(${zoomTransform.k})`,
  };

  const handleResetView = () => {
    setZoomTransform(d3.zoomIdentity);
    if (viewportRef.current) {
      d3.select(viewportRef.current).transition().duration(300).call(
        d3.zoom<HTMLDivElement, unknown>().transform as never,
        d3.zoomIdentity,
      );
    }
  };

  const handleCopyLink = async () => {
    await navigator.clipboard.writeText(window.location.href);
  };

  const handleExport = async () => {
    if (!exportRef.current) {
      return;
    }

    const canvas = await html2canvas(exportRef.current, {
      backgroundColor: '#020617',
      scale: 2,
    });

    const link = document.createElement('a');
    link.download = 'skintwin-cognitive-architecture.png';
    link.href = canvas.toDataURL('image/png');
    link.click();
  };

  const selectNode = (nodeId: string) => {
    setSelectedId(nodeId);
    setShowFinancial(nodeId === 'financial-overview' ? true : showFinancial);
  };

  const renderTriad = (triad: Triad) => {
    const isMatched = matchedNodeIds.has(triad.id) || triad.vertices.some((vertex) => matchedNodeIds.has(vertex.id));
    const isDimmed = searchQuery.trim().length > 0 && !isMatched;
    const isActive = activeStep.activeNodeIds.includes(triad.id);

    return (
      <div
        key={triad.id}
        className={`triad-card${selectedId === triad.id ? ' selected' : ''}${isDimmed ? ' dimmed' : ''}${isActive ? ' simulation-active' : ''}`}
        style={{ left: triad.position.x - TRIAD_SIZE / 2, top: triad.position.y - TRIAD_SIZE / 2 }}
        onClick={() => selectNode(triad.id)}
        role="button"
        tabIndex={0}
        onKeyDown={(event) => {
          if (event.key === 'Enter' || event.key === ' ') {
            event.preventDefault();
            selectNode(triad.id);
          }
        }}
      >
        <div className="triad-short-label">{triad.shortLabel}</div>
        <div className="triad-name">{triad.name}</div>
        <div className="triad-accounts">{triad.accountRange}</div>
        <div className="triad-coalescent">∀V∈{triad.shortLabel}</div>

        {triad.vertices.map((vertex) => renderVertex(triad, vertex))}
      </div>
    );
  };

  const renderVertex = (triad: Triad, vertex: Vertex) => {
    const isMatched = matchedNodeIds.has(vertex.id);
    const isDimmed = searchQuery.trim().length > 0 && !isMatched;
    const isActive = activeStep.activeNodeIds.includes(vertex.id);

    return (
      <button
        key={vertex.id}
        type="button"
        className={`vertex-node${selectedId === vertex.id ? ' selected' : ''}${isDimmed ? ' dimmed' : ''}${isActive ? ' simulation-active' : ''}`}
        style={{ left: TRIAD_SIZE / 2 + vertex.position.x - VERTEX_SIZE / 2, top: TRIAD_SIZE / 2 + vertex.position.y - VERTEX_SIZE / 2 }}
        onClick={(event) => {
          event.stopPropagation();
          selectNode(vertex.id);
        }}
        aria-label={`${triad.name} ${vertex.name}`}
      >
        {vertex.shortLabel}
      </button>
    );
  };

  const renderPeripheralNode = (node: PeripheralNode) => {
    const isMatched = matchedNodeIds.has(node.id);
    const isDimmed = searchQuery.trim().length > 0 && !isMatched;
    const isActive = activeStep.activeNodeIds.includes(node.id);

    return (
      <button
        key={node.id}
        type="button"
        className={`peripheral-node ${node.type}${selectedId === node.id ? ' selected' : ''}${isDimmed ? ' dimmed' : ''}${isActive ? ' simulation-active' : ''}`}
        style={{ left: node.position.x, top: node.position.y }}
        onClick={() => selectNode(node.id)}
      >
        <div className="peripheral-short-label">{node.shortLabel}</div>
        <div className="peripheral-title">{node.name}</div>
      </button>
    );
  };

  return (
    <div className="heptavertonic-page" ref={exportRef}>
      <header className="page-header">
        <div>
          <h1>Heptavertonic Organizational Model</h1>
          <p>Interactive cognitive architecture with financial integration, AI complements, and metacycle simulation.</p>
        </div>
        <div className="header-badges">
          <span>7 triads</span>
          <span>21 vertices</span>
          <span>Dynamic flows</span>
        </div>
      </header>

      <div className="visualization-layout">
        <section className="visualization-panel">
          <div className="controls-panel">
            <div className="search-group">
              <label htmlFor="architecture-search">Search architecture</label>
              <input
                id="architecture-search"
                type="search"
                placeholder="Find triads, accounts, or functions"
                value={searchQuery}
                onChange={(event) => setSearchQuery(event.target.value)}
              />
            </div>
            <div className="controls-grid">
              <button type="button" className={showFlows ? 'active' : ''} onClick={() => setShowFlows((current) => !current)}>
                {showFlows ? 'Hide Flows' : 'Show Flows'}
              </button>
              <button type="button" className={showBalance ? 'active' : ''} onClick={() => setShowBalance((current) => !current)}>
                {showBalance ? 'Hide Balance' : 'Show Balance'}
              </button>
              <button type="button" className={showFinancial ? 'active' : ''} onClick={() => setShowFinancial((current) => !current)}>
                {showFinancial ? 'Hide Financial' : 'Show Financial'}
              </button>
              <button type="button" className={animationRunning ? 'active' : ''} onClick={() => setAnimationRunning((current) => !current)}>
                {animationRunning ? 'Pause Motion' : 'Resume Motion'}
              </button>
              <button type="button" onClick={handleResetView}>Reset View</button>
              <button type="button" onClick={handleExport}>Export PNG</button>
              <button type="button" onClick={handleCopyLink}>Copy Link</button>
            </div>
          </div>

          <div className="balance-strip">
            {showBalance && (
              <>
                {([
                  ['Potential', 'potential', potentialRef],
                  ['Commitment', 'commitment', commitmentRef],
                  ['Performance', 'performance', performanceRef],
                  ['Field Coherence', 'coherence', coherenceRef],
                ] as const).map(([label, key, ref]) => (
                  <div className="balance-card" key={key}>
                    <div className="balance-card-header">
                      <span>{label}</span>
                      <strong>{Math.round(balanceState[key] * 100)}%</strong>
                    </div>
                    <div className="balance-bar">
                      <div
                        className="balance-fill"
                        ref={ref}
                        style={{ width: `${Math.round(balanceState[key] * 100)}%`, backgroundColor: getBalanceColor(balanceState[key]) }}
                      />
                    </div>
                  </div>
                ))}
              </>
            )}
          </div>

          <div className="viewport" ref={viewportRef}>
            <div className="workspace" style={transformStyle}>
              <div className="workspace-surface" style={{ width: CANVAS_WIDTH, height: CANVAS_HEIGHT }}>
                <div className="hemisphere right" />
                <div className="hemisphere left" />
                <div className="basal-system somatic" />
                <div className="basal-system limbic" />
                <div className="dimension-label potential" title="Potential Dimension">Potential Dimension</div>
                <div className="dimension-label commitment" title="Commitment Dimension">Commitment Dimension</div>
                <div className="dimension-label performance" title="Performance Dimension">Performance Dimension</div>

                <svg className="flow-layer" viewBox={`0 0 ${CANVAS_WIDTH} ${CANVAS_HEIGHT}`}>
                  <defs>
                    {Object.entries(flowStyleMap).map(([key, style]) => (
                      <marker key={key} id={`arrow-${key}`} viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
                        <path d="M 0 0 L 10 5 L 0 10 z" fill={style.color} />
                      </marker>
                    ))}
                  </defs>

                  {showFlows && FLOWS.map((flow) => {
                    const path = buildFlowPath(flow);
                    const midpoint = getQuadraticMidpoint(flow);
                    const style = flowStyleMap[flow.type];
                    const isActive = activeStep.activeFlowIds.includes(flow.id);
                    const isDimmed = searchQuery.trim().length > 0 && !matchedNodeIds.has(flow.from) && !matchedNodeIds.has(flow.to);
                    const opacity = isDimmed ? 0.15 : isActive ? 1 : 0.72;

                    return (
                      <g key={flow.id} className={isActive ? 'active-flow' : undefined}>
                        <path
                          id={flow.id}
                          d={path}
                          fill="none"
                          stroke={style.color}
                          strokeWidth={isActive ? 4 : 2.5}
                          strokeDasharray={style.dashArray}
                          markerEnd={`url(#arrow-${flow.type})`}
                          markerStart={flow.bidirectional ? `url(#arrow-${flow.type})` : undefined}
                          opacity={opacity}
                        />
                        <text x={midpoint.x} y={midpoint.y} fill={style.color} textAnchor="middle" dominantBaseline="middle" className="flow-label" opacity={opacity}>
                          {flow.label}
                        </text>
                        {animationRunning && (
                          <>
                            {[0, 1, 2].map((particleIndex) => (
                              <circle key={`${flow.id}-particle-${particleIndex}`} r="5" fill={style.color} opacity={opacity}>
                                <animateMotion dur={`${3 + particleIndex * 0.45}s`} repeatCount="indefinite" begin={`${particleIndex * 0.65}s`} path={path} />
                              </circle>
                            ))}
                            {flow.bidirectional && [0, 1].map((particleIndex) => (
                              <circle key={`${flow.id}-reverse-${particleIndex}`} r="5" fill={style.color} opacity={opacity * 0.9}>
                                <animateMotion dur={`${3.4 + particleIndex * 0.3}s`} repeatCount="indefinite" begin={`${particleIndex * 0.8}s`} path={buildFlowPath({ ...flow, from: flow.to, to: flow.from })} />
                              </circle>
                            ))}
                          </>
                        )}
                      </g>
                    );
                  })}
                </svg>

                {PERIPHERAL_NODES.map((node) => renderPeripheralNode(node))}
                {TRIADS.map((triad) => renderTriad(triad))}
              </div>
            </div>
          </div>
        </section>

        <aside className="insights-panel">
          <section className="simulation-panel">
            <div className="simulation-header">
              <h2>Metacycle Simulator</h2>
              <div className="simulation-actions">
                <button type="button" onClick={() => setSimulationPlaying((current) => !current)}>
                  {simulationPlaying ? 'Pause' : 'Simulate'}
                </button>
                <button type="button" onClick={() => setSimulationIndex((current) => (current - 1 + SIMULATION_STEPS.length) % SIMULATION_STEPS.length)}>
                  Prev
                </button>
                <button type="button" onClick={() => setSimulationIndex((current) => (current + 1) % SIMULATION_STEPS.length)}>
                  Next
                </button>
              </div>
            </div>
            <div className="simulation-step-counter">Step {simulationIndex + 1} of {SIMULATION_STEPS.length}</div>
            <h3>{activeStep.title}</h3>
            <p>{activeStep.description}</p>
          </section>

          <section className="info-panel">
            <div className="info-panel-header">
              <h2>{selectedDetails?.title ?? 'Explore the architecture'}</h2>
              {selectedDetails && (
                <button type="button" className="ghost-button" onClick={() => setSelectedId(showFinancial ? 'financial-overview' : null)}>
                  Close
                </button>
              )}
            </div>

            {selectedDetails ? (
              <>
                <div className="info-section">
                  <h3>Overview</h3>
                  <p className="info-subtitle">{selectedDetails.subtitle}</p>
                  <p>{selectedDetails.description}</p>
                </div>
                <div className="info-grid">
                  <div className="info-section">
                    <h3>Accounts</h3>
                    <p>{selectedDetails.accountRange ?? 'Cross-architecture'}</p>
                  </div>
                  <div className="info-section">
                    <h3>Dimension</h3>
                    <p>{selectedDetails.dimension}</p>
                  </div>
                </div>
                <div className="info-section">
                  <h3>Departments</h3>
                  <ul>
                    {selectedDetails.departments.map((department) => (
                      <li key={department}>{department}</li>
                    ))}
                  </ul>
                </div>
                <div className="info-section">
                  <h3>Financial</h3>
                  <ul>
                    {selectedDetails.financialSummary.map((line) => (
                      <li key={line}>{line}</li>
                    ))}
                  </ul>
                </div>
              </>
            ) : (
              <div className="info-empty-state">
                <p>Select a triad, vertex, or core subsystem to inspect its cognitive role, accounts, departments, and financial footprint.</p>
                <button type="button" onClick={() => setSelectedId('financial-overview')}>Open financial overview</button>
              </div>
            )}
          </section>
        </aside>
      </div>
    </div>
  );
};

export default HeptavertonicVisualization;
